name: Build and Release BWBundle

on:
  push:
    branches:
      - main
  schedule:
    - cron: '3 11 3 * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl xz-utils p7zip-full unzip python3 zstd libarchive-tools dpkg-dev

      - name: Build
        run: |
          chmod +x update-efi-binaries.sh
          ./update-efi-binaries.sh

          ZIP_NAME=$(ls bwbundle_fedora_alpha_*.zip)
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

          DATETIME=${ZIP_NAME#bwbundle-fedora-alpha_}
          DATETIME=${DATETIME%.zip}
          echo "DATETIME=$DATETIME" >> $GITHUB_ENV

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ github.event_name }}" = "schedule" ]; then
            REFRESH_NAME="bwbundle-fedora-alpha-refresh_${DATETIME}.zip"
            mv "$ZIP_NAME" "$REFRESH_NAME"
            gh release create "fedora_alpha_refresh-${DATETIME}" \
              --title "Fedora Alpha Build ${DATETIME}" \
              --notes $'Automated monthly refresh build from commit ${{ github.sha }}\n\nTo install copy zip contents to root of FAT32 media.\nEFI should be visible when you click on the drive.' \
              --prerelease \
              "$REFRESH_NAME"
          else
            gh release create "fedora-alpha-${DATETIME}" \
              --title "Fedora Alpha Build ${DATETIME}" \
              --notes $'Automated alpha build from commit ${{ github.sha }}\n\nTo install copy zip contents to root of FAT32 media.\nEFI should be visible when you click on the drive.' \
              "$ZIP_NAME"
          fi
